# Generated by Django 4.2.1 on 2023-09-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.CharField(max_length=20)),
                ('hora_ingreso', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('tiempo', models.CharField(max_length=20)),
                ('ruta', models.CharField(max_length=200)),
                ('dispositivo', models.CharField(max_length=20)),
            ],
        ),
    ]
